name: Release Windows

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build (package installer)
        run: npm run deploy

      - name: Create portable zip (win-unpacked)
        shell: pwsh
        run: |
          if (Test-Path 'release/win-unpacked') {
            Compress-Archive -Path 'release/win-unpacked/*' -DestinationPath 'release/opcua-tracer-portable.zip' -Force
          }

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-artifacts
          path: |
            release/*.exe
            release/opcua-tracer-portable.zip

      - name: Publish GitHub Release (on tag)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            release/*.exe
            release/opcua-tracer-portable.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
